import { to = module.networking.aws_vpc.this["vpc-0773253bc4daca414"] id = "vpc-0773253bc4daca414" }
import { to = module.networking.aws_vpc.this["vpc-056be321b2abea9e8"] id = "vpc-056be321b2abea9e8" }
import { to = module.networking.aws_subnet.this["subnet-091ec4941a1329ba6"] id = "subnet-091ec4941a1329ba6" }
import { to = module.networking.aws_subnet.this["subnet-0bbffd1611e131f53"] id = "subnet-0bbffd1611e131f53" }
import { to = module.networking.aws_subnet.this["subnet-0dbba8fd08a1a670c"] id = "subnet-0dbba8fd08a1a670c" }
import { to = module.networking.aws_subnet.this["subnet-0f50257b665d9cc1b"] id = "subnet-0f50257b665d9cc1b" }
import { to = module.networking.aws_subnet.this["subnet-0bcfe71370b0a0bd5"] id = "subnet-0bcfe71370b0a0bd5" }
import { to = module.networking.aws_subnet.this["subnet-0af3fca3903c44b7e"] id = "subnet-0af3fca3903c44b7e" }
import { to = module.networking.aws_subnet.this["subnet-0ad7ce7b0c00729fb"] id = "subnet-0ad7ce7b0c00729fb" }
import { to = module.networking.aws_subnet.this["subnet-0c69c5d9aef2f9d5a"] id = "subnet-0c69c5d9aef2f9d5a" }
import { to = module.networking.aws_subnet.this["subnet-0f21c4a72ec8443b0"] id = "subnet-0f21c4a72ec8443b0" }
import { to = module.networking.aws_subnet.this["subnet-0f46b98038512ea32"] id = "subnet-0f46b98038512ea32" }
import { to = module.networking.aws_subnet.this["subnet-0eb29715621020950"] id = "subnet-0eb29715621020950" }
import { to = module.networking.aws_subnet.this["subnet-04f05f3f9c3d2ccd7"] id = "subnet-04f05f3f9c3d2ccd7" }
import { to = module.networking.aws_subnet.this["subnet-0c1c87f9e579a9358"] id = "subnet-0c1c87f9e579a9358" }
import { to = module.networking.aws_route_table.this["rtb-0e5eab38184d44f98"] id = "rtb-0e5eab38184d44f98" }
import { to = module.networking.aws_route_table.this["rtb-01dd45b0eba367616"] id = "rtb-01dd45b0eba367616" }
import { to = module.networking.aws_route_table.this["rtb-03185d3e124e3a10d"] id = "rtb-03185d3e124e3a10d" }
import { to = module.networking.aws_route_table.this["rtb-0d6f24003f20450d2"] id = "rtb-0d6f24003f20450d2" }
import { to = module.networking.aws_route_table.this["rtb-010525e9dd5ea2605"] id = "rtb-010525e9dd5ea2605" }
import { to = module.networking.aws_route_table.this["rtb-02a5bfa5e52e64f10"] id = "rtb-02a5bfa5e52e64f10" }
import { to = module.networking.aws_route_table.this["rtb-07cdfc16bc2066ac1"] id = "rtb-07cdfc16bc2066ac1" }
import { to = module.networking.aws_route_table.this["rtb-0895712dce274bfd8"] id = "rtb-0895712dce274bfd8" }
import { to = module.networking.aws_nat_gateway.this["nat-032066e7e1c3d67a4"] id = "nat-032066e7e1c3d67a4" }
import { to = module.networking.aws_nat_gateway.this["nat-06465d3700d7d8337"] id = "nat-06465d3700d7d8337" }
import { to = module.security_groups.aws_security_group.this["prod_vpc_internal_traffic"] id = "sg-0a3e289da76de0353" }
import { to = module.security_groups.aws_security_group.this["linux_bastion"] id = "sg-0596e9366f2299407" }
import { to = module.security_groups.aws_security_group.this["sapiens_data_rpl_db_dev_sg"] id = "sg-0be9a2b7d42034fac" }
import { to = module.security_groups.aws_security_group.this["constructioncapacityapi_ebs_security"] id = "sg-0997987b6834efa73" }
import { to = module.security_groups.aws_security_group.this["sapiens_data_rpl_db_prod_sg"] id = "sg-0897b83200c529324" }
import { to = module.security_groups.aws_security_group.this["microsoft_windows_server_2019_base_2022_02_10_autogenbyawsmp"] id = "sg-0b6a8073540c1cb9a" }
import { to = module.security_groups.aws_security_group.this["awseb_e_t2wrbbxesn_stack_awsebsecuritygroup_17z98mkyxwdoa"] id = "sg-0985bc300f673015a" }
import { to = module.security_groups.aws_security_group.this["microsoft_windows_server_2019_base_2022_02_10_autogenbyawsmp"] id = "sg-0da6cc2bc59441b15" }
import { to = module.security_groups.aws_security_group.this["default"] id = "sg-02a5358cd707eee5c" }
import { to = module.security_groups.aws_security_group.this["constructioncapacity_rds_dev"] id = "sg-0e9b70067d7334c56" }
import { to = module.security_groups.aws_security_group.this["default"] id = "sg-080f28d7569af1b80" }
import { to = module.security_groups.aws_security_group.this["intact_dev_glue_sg"] id = "sg-04815e9ede6f75abc" }
import { to = module.security_groups.aws_security_group.this["intact_prod_glue_sg"] id = "sg-0ae915b71b9ca13b5" }
import { to = module.security_groups.aws_security_group.this["construction_job_trigger_prod_lambda_sg"] id = "sg-0ed15004f60fe5ddf" }
import { to = module.security_groups.aws_security_group.this["bastion_windows"] id = "sg-0df12569ecaa6569a" }
import { to = module.security_groups.aws_security_group.this["intact_allow_traffic_to_prod_vpc"] id = "sg-08389ac9ffe6a06f7" }
import { to = module.security_groups.aws_security_group.this["constructioncapacity_rds_prod"] id = "sg-062b09810708db6ef" }
import { to = module.security_groups.aws_security_group.this["linux_bastion_prod_vpc"] id = "sg-0374bef6b6effcd1c" }
import { to = module.security_groups.aws_security_group.this["awseb_e_rf8gah3j8s_stack_awsebsecuritygroup_53u52xnkral6"] id = "sg-0a91845af00af000d" }
import { to = module.security_groups.aws_security_group.this["awseb_e_rf8gah3j8s_stack_awsebloadbalancersecuritygroup_1kbh"] id = "sg-0721a3e0f69333439" }
import { to = module.security_groups.aws_security_group.this["awseb_e_t2wrbbxesn_stack_awsebloadbalancersecuritygroup_1sz1"] id = "sg-0f5616250eb4610eb" }
import { to = module.ec2.aws_instance.this["tmh-access"] id = "i-01bf910b0fffef645" }
import { to = module.ec2.aws_instance.this["tmh-access"] id = "i-0c93e509ed5de753b" }
import { to = module.ec2.aws_instance.this["tmh-access"] id = "i-0925b39208a811c79" }
import { to = module.ec2.aws_instance.this["tmh-access"] id = "i-0494330f6f3703475" }
import { to = module.ec2.aws_instance.this["tmh-access"] id = "i-0e77b7407210b1d6d" }
import { to = module.ec2.aws_instance.this["tmh-access"] id = "i-0c3382fc761a2b5a1" }
import { to = module.ec2.aws_instance.this["tmh-access"] id = "i-0f22f8241409b34bd" }
import { to = module.ec2.aws_instance.this["tmh-access"] id = "i-07fa6c136eea9c03c" }
import { to = module.alb.aws_lb.this["constructioncapacity_api_dev_nlb"] id = "arn:aws:elasticloadbalancing:us-east-2:401157580704:loadbalancer/net/ConstructionCapacity-api-dev-nlb/b9f62a0723a6ad66" }
import { to = module.alb.aws_lb.this["constructioncapacityapi_prod_nlb"] id = "arn:aws:elasticloadbalancing:us-east-2:401157580704:loadbalancer/net/constructioncapacityapi-prod-nlb/e9184833c2c1b7fc" }
import { to = module.alb.aws_lb.this["awseb_awseb_zo7qrx88vt24"] id = "arn:aws:elasticloadbalancing:us-east-2:401157580704:loadbalancer/app/awseb-AWSEB-ZO7QRX88VT24/c0eb7e5c284721e3" }
import { to = module.alb.aws_lb.this["awseb_awseb_15yb24hygypze"] id = "arn:aws:elasticloadbalancing:us-east-2:401157580704:loadbalancer/app/awseb-AWSEB-15YB24HYGYPZE/acee8aa2180f09e0" }
import { to = module.alb.aws_lb_target_group.this["constructioncapacity_api_dev_tg"] id = "arn:aws:elasticloadbalancing:us-east-2:401157580704:targetgroup/ConstructionCapacity-api-dev-tg/708b4401e481e7d6" }
import { to = module.alb.aws_lb_target_group.this["awseb_awseb_5und5ogli120"] id = "arn:aws:elasticloadbalancing:us-east-2:401157580704:targetgroup/awseb-AWSEB-5UND5OGLI120/41c91f107e497aa9" }
import { to = module.alb.aws_lb_target_group.this["awseb_awseb_c3ucimxxgwe1"] id = "arn:aws:elasticloadbalancing:us-east-2:401157580704:targetgroup/awseb-AWSEB-C3UCIMXXGWE1/de2c3a618de420cc" }
import { to = module.alb.aws_lb_target_group.this["constructioncapacity_api_prod_tg"] id = "arn:aws:elasticloadbalancing:us-east-2:401157580704:targetgroup/constructionCapacity-api-prod-tg/362bc45903cfb60e" }
import { to = module.rds.aws_db_instance.this["ark_construction_db_dev_new"] id = "ark-construction-db-dev-new" }
import { to = module.rds.aws_db_instance.this["ark_construction_db_prod_new"] id = "ark-construction-db-prod-new" }
import { to = module.rds.aws_db_instance.this["constructioncapacityapi_db_dev"] id = "constructioncapacityapi-db-dev" }
import { to = module.rds.aws_db_instance.this["constructioncapacityapi_db_prod"] id = "constructioncapacityapi-db-prod" }
import { to = module.rds.aws_db_instance.this["sapiens_data_rpl_db_dev"] id = "sapiens-data-rpl-db-dev" }
import { to = module.rds.aws_db_instance.this["sapiens_data_rpl_db_prod"] id = "sapiens-data-rpl-db-prod" }
import { to = module.s3.aws_s3_bucket.this["accesslogsforapploadbalancer"] id = "accesslogsforapploadbalancer" }
import { to = module.s3.aws_s3_bucket.this["ark_construction_dev_backup"] id = "ark-construction-dev-backup" }
import { to = module.s3.aws_s3_bucket.this["ark_construction_dev_s3"] id = "ark-construction-dev-s3" }
import { to = module.s3.aws_s3_bucket.this["ark_construction_prod_backup"] id = "ark-construction-prod-backup" }
import { to = module.s3.aws_s3_bucket.this["ark_construction_prod_s3"] id = "ark-construction-prod-s3" }
import { to = module.s3.aws_s3_bucket.this["aws_glue_assets_401157580704_us_east_2"] id = "aws-glue-assets-401157580704-us-east-2" }
import { to = module.s3.aws_s3_bucket.this["aws_glue_scripts_401157580704_us_east_2"] id = "aws-glue-scripts-401157580704-us-east-2" }
import { to = module.s3.aws_s3_bucket.this["aws_glue_temporary_401157580704_us_east_2"] id = "aws-glue-temporary-401157580704-us-east-2" }
import { to = module.s3.aws_s3_bucket.this["aws_quicksetup_patchpolicy_access_log_401157580704_nhwet"] id = "aws-quicksetup-patchpolicy-access-log-401157580704-nhwet" }
import { to = module.s3.aws_s3_bucket.this["aws_quicksetup_patchpolicy_access_log_401157580704_o14sn"] id = "aws-quicksetup-patchpolicy-access-log-401157580704-o14sn" }
import { to = module.s3.aws_s3_bucket.this["cf_templates_acja80sq5xwi_us_east_2"] id = "cf-templates-acja80sq5xwi-us-east-2" }
import { to = module.s3.aws_s3_bucket.this["config_bucket_401157580704"] id = "config-bucket-401157580704" }
import { to = module.s3.aws_s3_bucket.this["construction_powerbi_files"] id = "construction-powerbi-files" }
import { to = module.s3.aws_s3_bucket.this["constructioncapacityapi_prod_nlb_logs"] id = "constructioncapacityapi-prod-nlb-logs" }
import { to = module.s3.aws_s3_bucket.this["elasticbeanstalk_us_east_1_401157580704"] id = "elasticbeanstalk-us-east-1-401157580704" }
import { to = module.s3.aws_s3_bucket.this["elasticbeanstalk_us_east_2_401157580704"] id = "elasticbeanstalk-us-east-2-401157580704" }
import { to = module.s3.aws_s3_bucket.this["external_scripts_py"] id = "external-scripts-py" }
import { to = module.s3.aws_s3_bucket.this["intact_cloudtrail_logs_central"] id = "intact-cloudtrail-logs-central" }
import { to = module.s3.aws_s3_bucket.this["intact_cost_and_usage_report_cur_bucket"] id = "intact-cost-and-usage-report-cur-bucket" }
import { to = module.s3.aws_s3_bucket.this["intact_ec2_patch_logs_dev"] id = "intact-ec2-patch-logs-dev" }
import { to = module.s3.aws_s3_bucket.this["intact_prod_ct_central"] id = "intact-prod-ct-central" }
import { to = module.s3.aws_s3_bucket.this["intact_rds_data_dump"] id = "intact-rds-data-dump" }
import { to = module.s3.aws_s3_bucket.this["intact_security_hub_findings_prg_py"] id = "intact-security-hub-findings-prg-py" }
import { to = module.s3.aws_s3_bucket.this["intact_server_access_logs_s3"] id = "intact-server-access-logs-s3" }
import { to = module.s3.aws_s3_bucket.this["intact_server_access_logs_s3_us_east_1"] id = "intact-server-access-logs-s3-us-east-1" }
import { to = module.s3.aws_s3_bucket.this["monthly_bills_excelfile"] id = "monthly-bills-excelfile" }
import { to = module.s3.aws_s3_bucket.this["sapiens_replication_data"] id = "sapiens-replication-data" }
import { to = module.s3.aws_s3_bucket.this["terraform_state_intact"] id = "terraform-state-intact" }
import { to = module.iam.aws_iam_role.this["amazon_glueserviceroleforssm"] id = "Amazon-GlueServiceRoleForSSM" }
import { to = module.iam.aws_iam_role.this["amazonssmroleforinstancesquicksetup"] id = "AmazonSSMRoleForInstancesQuickSetup" }
import { to = module.iam.aws_iam_role.this["amazon_eventbridge_invoke_lambda"] id = "Amazon_EventBridge_Invoke_Lambda" }
import { to = module.iam.aws_iam_role.this["amazon_eventbridge_invoke_lambda_1520644468"] id = "Amazon_EventBridge_Invoke_Lambda_1520644468" }
import { to = module.iam.aws_iam_role.this["amazon_eventbridge_invoke_sns_1488555510"] id = "Amazon_EventBridge_Invoke_Sns_1488555510" }
import { to = module.iam.aws_iam_role.this["amazon_eventbridge_invoke_sns_1844644364"] id = "Amazon_EventBridge_Invoke_Sns_1844644364" }
import { to = module.iam.aws_iam_role.this["amazon_eventbridge_invoke_sns_912770784"] id = "Amazon_EventBridge_Invoke_Sns_912770784" }
import { to = module.iam.aws_iam_role.this["amazon_eventbridge_scheduler_lambda_c592caf04d"] id = "Amazon_EventBridge_Scheduler_LAMBDA_c592caf04d" }
import { to = module.iam.aws_iam_role.this["ark_construction_prod_s3_acess_role"] id = "ark-construction-prod-s3-acess-role" }
import { to = module.iam.aws_iam_role.this["aws_api_gateway_cloudwatchlogs"] id = "aws-api-gateway-cloudwatchlogs" }
import { to = module.iam.aws_iam_role.this["aws_ec2_spot_fleet_tagging_role"] id = "aws-ec2-spot-fleet-tagging-role" }
import { to = module.iam.aws_iam_role.this["aws_elasticbeanstalk_ec2_role"] id = "aws-elasticbeanstalk-ec2-role" }
import { to = module.iam.aws_iam_role.this["aws_elasticbeanstalk_service_role"] id = "aws-elasticbeanstalk-service-role" }
import { to = module.iam.aws_iam_role.this["aws_glue_state_custom_email_role_sl90xr1e"] id = "AWS-Glue-state-custom-email-role-sl90xr1e" }
import { to = module.iam.aws_iam_role.this["aws_quicksetup_ssm_roleforenablingexplorer"] id = "AWS-QuickSetup-SSM-RoleForEnablingExplorer" }
import { to = module.iam.aws_iam_role.this["aws_quicksetup_stackset_local_administrationrole"] id = "AWS-QuickSetup-StackSet-Local-AdministrationRole" }
import { to = module.iam.aws_iam_role.this["aws_quicksetup_stackset_local_executionrole"] id = "AWS-QuickSetup-StackSet-Local-ExecutionRole" }
import { to = module.iam.aws_iam_role.this["awsbackupdefaultservicerole"] id = "AWSBackupDefaultServiceRole" }
import { to = module.iam.aws_iam_role.this["awsglueservicerole_demo"] id = "AWSGlueServiceRole-demo" }
import { to = module.iam.aws_iam_role.this["awsreservedsso_az_app_aws_developer_dev_prod_6064d4f146e180c"] id = "AWSReservedSSO_AZ-APP-AWS-Developer-Dev-Prod_6064d4f146e180c7" }
import { to = module.iam.aws_iam_role.this["awsreservedsso_az_app_aws_organization_admins_b8b7161f4b17c7"] id = "AWSReservedSSO_AZ-APP-AWS-Organization-Admins_b8b7161f4b17c7e8" }
import { to = module.iam.aws_iam_role.this["awsreservedsso_az_app_aws_platform_billing_ac3f9c119cd3cf3d"] id = "AWSReservedSSO_AZ-APP-AWS-Platform-Billing_ac3f9c119cd3cf3d" }
import { to = module.iam.aws_iam_role.this["awsreservedsso_az_app_aws_poweruseraccess_2154bff77cb538f0"] id = "AWSReservedSSO_AZ-APP-AWS-PowerUserAccess_2154bff77cb538f0" }
import { to = module.iam.aws_iam_role.this["awsreservedsso_az_app_aws_readonly_dev_prod_d62e7a1d60ac3843"] id = "AWSReservedSSO_AZ-APP-AWS-Readonly-Dev-Prod_d62e7a1d60ac3843" }
import { to = module.iam.aws_iam_role.this["awsserviceroleforaccessanalyzer"] id = "AWSServiceRoleForAccessAnalyzer" }
import { to = module.iam.aws_iam_role.this["awsserviceroleforamazonguardduty"] id = "AWSServiceRoleForAmazonGuardDuty" }
import { to = module.iam.aws_iam_role.this["awsserviceroleforamazonguarddutymalwareprotection"] id = "AWSServiceRoleForAmazonGuardDutyMalwareProtection" }
import { to = module.iam.aws_iam_role.this["awsserviceroleforamazoninspector"] id = "AWSServiceRoleForAmazonInspector" }
import { to = module.iam.aws_iam_role.this["awsserviceroleforamazoninspector2"] id = "AWSServiceRoleForAmazonInspector2" }
import { to = module.iam.aws_iam_role.this["awsserviceroleforamazonssm"] id = "AWSServiceRoleForAmazonSSM" }
import { to = module.iam.aws_iam_role.this["awsserviceroleforamazonssm_accountdiscovery"] id = "AWSServiceRoleForAmazonSSM_AccountDiscovery" }
import { to = module.iam.aws_iam_role.this["awsserviceroleforapigateway"] id = "AWSServiceRoleForAPIGateway" }
import { to = module.iam.aws_iam_role.this["awsserviceroleforapplicationautoscaling_dynamodbtable"] id = "AWSServiceRoleForApplicationAutoScaling_DynamoDBTable" }
import { to = module.iam.aws_iam_role.this["awsserviceroleforautoscaling"] id = "AWSServiceRoleForAutoScaling" }
import { to = module.iam.aws_iam_role.this["awsserviceroleforawslicensemanagerrole"] id = "AWSServiceRoleForAWSLicenseManagerRole" }
import { to = module.iam.aws_iam_role.this["awsserviceroleforawslicensemanagerusersubscriptionsservice"] id = "AWSServiceRoleForAWSLicenseManagerUserSubscriptionsService" }
import { to = module.iam.aws_iam_role.this["awsserviceroleforbackup"] id = "AWSServiceRoleForBackup" }
import { to = module.iam.aws_iam_role.this["awsserviceroleforbackupreports"] id = "AWSServiceRoleForBackupReports" }
import { to = module.iam.aws_iam_role.this["awsserviceroleforcloudformationstacksetsorgadmin"] id = "AWSServiceRoleForCloudFormationStackSetsOrgAdmin" }
import { to = module.iam.aws_iam_role.this["awsserviceroleforcomputeoptimizer"] id = "AWSServiceRoleForComputeOptimizer" }
import { to = module.iam.aws_iam_role.this["awsserviceroleforconfig"] id = "AWSServiceRoleForConfig" }
import { to = module.iam.aws_iam_role.this["awsserviceroleforelasticbeanstalk"] id = "AWSServiceRoleForElasticBeanstalk" }
import { to = module.iam.aws_iam_role.this["awsserviceroleforelasticbeanstalkmanagedupdates"] id = "AWSServiceRoleForElasticBeanstalkManagedUpdates" }
import { to = module.iam.aws_iam_role.this["awsserviceroleforelasticloadbalancing"] id = "AWSServiceRoleForElasticLoadBalancing" }
import { to = module.iam.aws_iam_role.this["awsserviceroleforglobalaccelerator"] id = "AWSServiceRoleForGlobalAccelerator" }
import { to = module.iam.aws_iam_role.this["awsserviceroleforincidentmanager"] id = "AWSServiceRoleForIncidentManager" }
import { to = module.iam.aws_iam_role.this["awsserviceroleforkeymanagementservicemultiregionkeys"] id = "AWSServiceRoleForKeyManagementServiceMultiRegionKeys" }
import { to = module.iam.aws_iam_role.this["awsserviceroleformarketplacelicensemanagement"] id = "AWSServiceRoleForMarketplaceLicenseManagement" }
import { to = module.iam.aws_iam_role.this["awsservicerolefororganizations"] id = "AWSServiceRoleForOrganizations" }
import { to = module.iam.aws_iam_role.this["awsserviceroleforrds"] id = "AWSServiceRoleForRDS" }
import { to = module.iam.aws_iam_role.this["awsserviceroleforresourceexplorer"] id = "AWSServiceRoleForResourceExplorer" }
import { to = module.iam.aws_iam_role.this["awsserviceroleforsecurityhub"] id = "AWSServiceRoleForSecurityHub" }
import { to = module.iam.aws_iam_role.this["awsserviceroleforssmquicksetup"] id = "AWSServiceRoleForSSMQuickSetup" }
import { to = module.iam.aws_iam_role.this["awsserviceroleforsso"] id = "AWSServiceRoleForSSO" }
import { to = module.iam.aws_iam_role.this["awsserviceroleforsupport"] id = "AWSServiceRoleForSupport" }
import { to = module.iam.aws_iam_role.this["awsserviceroleforsystemsmanageropsdatasync"] id = "AWSServiceRoleForSystemsManagerOpsDataSync" }
import { to = module.iam.aws_iam_role.this["awsservicerolefortrustedadvisor"] id = "AWSServiceRoleForTrustedAdvisor" }
import { to = module.iam.aws_iam_role.this["awsserviceroleforvpctransitgateway"] id = "AWSServiceRoleForVPCTransitGateway" }
import { to = module.iam.aws_iam_role.this["awstransferloggingaccess"] id = "AWSTransferLoggingAccess" }
import { to = module.iam.aws_iam_role.this["aws_inspectorevents_invoke_assessment_template"] id = "AWS_InspectorEvents_Invoke_Assessment_Template" }
import { to = module.iam.aws_iam_role.this["aws_lambda_apigateway"] id = "AWS_Lambda_APIGateway" }
import { to = module.iam.aws_iam_role.this["aws_sso_azuread_role"] id = "AWS_SSO_AZUREAD_Role" }
import { to = module.iam.aws_iam_role.this["azure_ad_custom_role"] id = "Azure_AD_custom_role" }
import { to = module.iam.aws_iam_role.this["cloudtrailroleforcloudwatchlogs"] id = "cloudtrailroleforcloudwatchlogs" }
import { to = module.iam.aws_iam_role.this["cloudtrailrolefor_cloudwatchlogs"] id = "cloudtrailrolefor_cloudwatchlogs" }
import { to = module.iam.aws_iam_role.this["codebuild_construction_capacity_api_dev_service_role"] id = "codebuild-construction-capacity-api-dev-service-role" }
import { to = module.iam.aws_iam_role.this["codebuild_construction_capacity_api_prod_service_role"] id = "codebuild-construction-capacity-api-prod-service-role" }
import { to = module.iam.aws_iam_role.this["consolelogin_authentication_failures_role_f8qvnkld"] id = "Consolelogin_authentication_failures-role-f8qvnkld" }
import { to = module.iam.aws_iam_role.this["construction_s3_user"] id = "construction-s3-user" }
import { to = module.iam.aws_iam_role.this["construction_capacity_jobs_role"] id = "construction_capacity_jobs_role" }
import { to = module.iam.aws_iam_role.this["custom_email_for_ec2_and_rds_role_uti6gop0"] id = "Custom-email-for-EC2-and-RDS-role-uti6gop0" }
import { to = module.iam.aws_iam_role.this["intact_cmp_tool"] id = "intact-cmp-tool" }
import { to = module.iam.aws_iam_role.this["intact_highland_dev_developer"] id = "intact-highland-dev-developer" }
import { to = module.iam.aws_iam_role.this["intact_security_hub_findi_custominsightslambdaexec_solddf0re"] id = "intact-security-hub-findi-CustomInsightsLambdaExec-SOLDDF0RE1OD" }
import { to = module.iam.aws_iam_role.this["intact_security_hub_findi_sendemaillambdaexecution_24ku1myoy"] id = "intact-security-hub-findi-SendEmailLambdaExecution-24KU1MYOYMVL" }
import { to = module.iam.aws_iam_role.this["intact_securityaudit_role"] id = "Intact-SecurityAudit-Role" }
import { to = module.iam.aws_iam_role.this["intact_ssm_ec2_role"] id = "intact-ssm-ec2-role" }
import { to = module.iam.aws_iam_role.this["opsitem_cwe_role"] id = "OpsItem-CWE-Role" }
import { to = module.iam.aws_iam_role.this["rds_monitoring_role"] id = "rds-monitoring-role" }
import { to = module.iam.aws_iam_role.this["rds_s3_role"] id = "RDS_S3_Role" }
import { to = module.iam.aws_iam_role.this["rolefor_ssm_triggers_sns"] id = "rolefor_SSM_Triggers_SNS" }
import { to = module.iam.aws_iam_role.this["role_for_ssm_topatch_ec2"] id = "Role_for_SSM_toPatch_EC2" }
import { to = module.iam.aws_iam_role.this["s3_sns_publish"] id = "s3_sns_publish" }
import { to = module.iam.aws_iam_role.this["secretsmanager_key_rotation_lambda_role_fr0zw7k2"] id = "Secretsmanager-key-rotation-lambda-role-fr0zw7k2" }
import { to = module.iam.aws_iam_role.this["securityhubprocessor_role_ib304swr"] id = "SecurityHubProcessor-role-ib304swr" }
import { to = module.iam.aws_iam_role.this["snsfailurefeedback"] id = "SNSFailureFeedback" }
import { to = module.iam.aws_iam_role.this["snssuccessfeedback"] id = "SNSSuccessFeedback" }
import { to = module.iam.aws_iam_role.this["sns_delivery_status_logging_role_tp5l4bc6"] id = "SNS_Delivery_Status_Logging-role-tp5l4bc6" }
import { to = module.iam.aws_iam_role.this["supportincidentmanagementrole"] id = "SupportIncidentManagementRole" }
import { to = module.iam.aws_iam_role.this["vpcflowlogs_cloudwatch_1745232994923"] id = "VPCFlowLogs-Cloudwatch-1745232994923" }
import { to = module.iam.aws_iam_role.this["vpcflowlogstocloudwatchloggroup"] id = "vpcflowlogstocloudwatchloggroup" }
import { to = module.iam.aws_iam_role.this["weekly_resource_inventory"] id = "Weekly_Resource_Inventory" }
import { to = module.eventbridge.aws_cloudwatch_event_rule.this["amazon_inspector_assessment_0_zickaonu_iddvn4d"] id = "Amazon_Inspector_Assessment_0-ZiCKaOnu_IdDvN4D" }
import { to = module.eventbridge.aws_cloudwatch_event_rule.this["amazon_inspector_assessment_0_zickaonu_idhszea"] id = "Amazon_Inspector_Assessment_0-ZiCKaOnu_IdHszea" }
import { to = module.eventbridge.aws_cloudwatch_event_rule.this["amazon_inspector_assessment_0_zickaonu_idi9bbc"] id = "Amazon_Inspector_Assessment_0-ZiCKaOnu_IdI9BbC" }
import { to = module.eventbridge.aws_cloudwatch_event_rule.this["amazon_inspector_assessment_0_zickaonu_idplj0m"] id = "Amazon_Inspector_Assessment_0-ZiCKaOnu_IdPlj0m" }
import { to = module.eventbridge.aws_cloudwatch_event_rule.this["amazon_inspector_assessment_0_bbddfo1a_idim2us"] id = "Amazon_Inspector_Assessment_0-bBDDFo1A_IdIM2uS" }
import { to = module.eventbridge.aws_cloudwatch_event_rule.this["amazon_inspector_assessment_0_jgkjhqez_idro5px"] id = "Amazon_Inspector_Assessment_0-jgkJHqez_IdrO5px" }
import { to = module.eventbridge.aws_cloudwatch_event_rule.this["amazon_inspector_assessment_0_jgkjhqez_idxdjed"] id = "Amazon_Inspector_Assessment_0-jgkJHqez_IdxDJed" }
import { to = module.eventbridge.aws_cloudwatch_event_rule.this["change_in_iam"] id = "Change-in-IAM" }
import { to = module.eventbridge.aws_cloudwatch_event_rule.this["do_not_delete_amazoninspectorec2managedrule"] id = "DO-NOT-DELETE-AmazonInspectorEc2ManagedRule" }
import { to = module.eventbridge.aws_cloudwatch_event_rule.this["do_not_delete_amazoninspectorec2tagmanagedrule"] id = "DO-NOT-DELETE-AmazonInspectorEc2TagManagedRule" }
import { to = module.eventbridge.aws_cloudwatch_event_rule.this["guardduty_finding_alerts"] id = "GuardDuty-Finding-Alerts" }
import { to = module.eventbridge.aws_cloudwatch_event_rule.this["intact_ec2_availability_p1"] id = "INTACT_EC2_Availability_P1" }
import { to = module.eventbridge.aws_cloudwatch_event_rule.this["intact_glue_job_state_change_p1"] id = "INTACT_GLUE_job_state_change_P1" }
import { to = module.eventbridge.aws_cloudwatch_event_rule.this["monitor_routetable_changes"] id = "Monitor-routetable-changes" }
import { to = module.eventbridge.aws_cloudwatch_event_rule.this["ssmexplorermanagedrule"] id = "SSMExplorerManagedRule" }
import { to = module.eventbridge.aws_cloudwatch_event_rule.this["ssmopsitems_autoscaling_instance_launch_failure"] id = "SSMOpsItems-Autoscaling-instance-launch-failure" }
import { to = module.eventbridge.aws_cloudwatch_event_rule.this["ssmopsitems_autoscaling_instance_termination_failure"] id = "SSMOpsItems-Autoscaling-instance-termination-failure" }
import { to = module.eventbridge.aws_cloudwatch_event_rule.this["ssmopsitems_ebs_snapshot_copy_failed"] id = "SSMOpsItems-EBS-snapshot-copy-failed" }
import { to = module.eventbridge.aws_cloudwatch_event_rule.this["ssmopsitems_ebs_snapshot_creation_failed"] id = "SSMOpsItems-EBS-snapshot-creation-failed" }
import { to = module.eventbridge.aws_cloudwatch_event_rule.this["ssmopsitems_ebs_volume_performance_issue"] id = "SSMOpsItems-EBS-volume-performance-issue" }
import { to = module.eventbridge.aws_cloudwatch_event_rule.this["ssmopsitems_ec2_issue"] id = "SSMOpsItems-EC2-issue" }
import { to = module.eventbridge.aws_cloudwatch_event_rule.this["ssmopsitems_ec2_scheduled_change"] id = "SSMOpsItems-EC2-scheduled-change" }
import { to = module.eventbridge.aws_cloudwatch_event_rule.this["ssmopsitems_rds_issue"] id = "SSMOpsItems-RDS-issue" }
import { to = module.eventbridge.aws_cloudwatch_event_rule.this["ssmopsitems_rds_scheduled_change"] id = "SSMOpsItems-RDS-scheduled-change" }
import { to = module.eventbridge.aws_cloudwatch_event_rule.this["ssmopsitems_ssm_maintenance_window_execution_failed"] id = "SSMOpsItems-SSM-maintenance-window-execution-failed" }
import { to = module.eventbridge.aws_cloudwatch_event_rule.this["ssmopsitems_ssm_maintenance_window_execution_timedout"] id = "SSMOpsItems-SSM-maintenance-window-execution-timedout" }
import { to = module.eventbridge.aws_cloudwatch_event_rule.this["securityhuballalerts"] id = "SecurityHubAllAlerts" }
import { to = module.eventbridge.aws_cloudwatch_event_rule.this["securityhubsummaryemailschedule"] id = "SecurityHubSummaryEmailSchedule" }
import { to = module.eventbridge.aws_cloudwatch_event_rule.this["cloud_formation_templatechange"] id = "cloud-formation-templatechange" }
import { to = module.eventbridge.aws_cloudwatch_event_rule.this["console_login"] id = "console_login" }
import { to = module.eventbridge.aws_cloudwatch_event_rule.this["rule_sns_topic_all_topics_default"] id = "rule_SNS_topic_ALL_TOPICS_DEFAULT" }
import { to = module.eventbridge.aws_cloudwatch_event_rule.this["rule_alb_all_events"] id = "rule_alb_all_events" }
import { to = module.eventbridge.aws_cloudwatch_event_rule.this["rule_api_gateway_all_events"] id = "rule_api_gateway_all_events" }
import { to = module.eventbridge.aws_cloudwatch_event_rule.this["rule_beanstalk_all_events"] id = "rule_beanstalk_all_events" }
import { to = module.eventbridge.aws_cloudwatch_event_rule.this["rule_cloud_watch_all_events"] id = "rule_cloud_watch_all_events" }
import { to = module.eventbridge.aws_cloudwatch_event_rule.this["rule_cloud_watch_logs_all_events"] id = "rule_cloud_watch_logs_all_events" }
import { to = module.eventbridge.aws_cloudwatch_event_rule.this["rule_ec2_all_events"] id = "rule_ec2_all_events" }
import { to = module.eventbridge.aws_cloudwatch_event_rule.this["rule_glue_all_events"] id = "rule_glue_all_events" }
import { to = module.eventbridge.aws_cloudwatch_event_rule.this["rule_lambda_all_events"] id = "rule_lambda_all_events" }
import { to = module.eventbridge.aws_cloudwatch_event_rule.this["rule_rds_all_events"] id = "rule_rds_all_events" }
import { to = module.eventbridge.aws_cloudwatch_event_rule.this["security_hub_findings"] id = "security_hub_findings" }
import { to = module.eventbridge.aws_cloudwatch_event_rule.this["weekly_inventory_report"] id = "weekly-inventory-report" }
import { to = module.cloudwatch.aws_cloudwatch_metric_alarm.this["cloudtrail_aws_configuration_changes"] id = "CloudTrail_AWS_Configuration_changes" }
import { to = module.cloudwatch.aws_cloudwatch_metric_alarm.this["config_configuration_changes"] id = "Config_configuration_changes" }
import { to = module.cloudwatch.aws_cloudwatch_metric_alarm.this["iam_policy_changes"] id = "IAM_policy_changes" }
import { to = module.cloudwatch.aws_cloudwatch_metric_alarm.this["intact_alb_awseb_awseb_15yb24hygypze_5xxs_p1"] id = "INTACT_ALB_awseb-AWSEB-15YB24HYGYPZE_5XXs_P1" }
import { to = module.cloudwatch.aws_cloudwatch_metric_alarm.this["intact_alb_awseb_awseb_zo7qrx88vt24_5xxs_p2"] id = "INTACT_ALB_awseb-AWSEB-ZO7QRX88VT24_5XXs_P2" }
import { to = module.cloudwatch.aws_cloudwatch_metric_alarm.this["intact_apigateway_construction_capacity_api_sapiens_4xxerror"] id = "INTACT_APIgateway_construction-capacity-api-Sapiens_4xxError_P2" }
import { to = module.cloudwatch.aws_cloudwatch_metric_alarm.this["intact_apigateway_construction_capacity_api_sapiens_5xxerror"] id = "INTACT_APIgateway_construction-capacity-api-Sapiens_5xxError_P2" }
import { to = module.cloudwatch.aws_cloudwatch_metric_alarm.this["intact_apigateway_construction_capacity_api_prod_sapiens_4xx"] id = "INTACT_APIgateway_construction-capacity-api-prod-Sapiens_4xxError_P1" }
import { to = module.cloudwatch.aws_cloudwatch_metric_alarm.this["intact_apigateway_construction_capacity_api_prod_sapiens_5xx"] id = "INTACT_APIgateway_construction-capacity-api-prod-Sapiens_5xxError_P1" }
import { to = module.cloudwatch.aws_cloudwatch_metric_alarm.this["intact_ec2_powerbi_desktop_new_cpuutilization_p2_s1_95_per"] id = "INTACT_EC2_Powerbi-Desktop-new_CPUUtilization_P2_S1_95_Per" }
import { to = module.cloudwatch.aws_cloudwatch_metric_alarm.this["intact_ec2_powerbi_desktop_prod_new_cpuutilization_p1_s1_90_"] id = "INTACT_EC2_Powerbi-Desktop-prod-new_CPUUtilization_P1_S1_90_Per" }
import { to = module.cloudwatch.aws_cloudwatch_metric_alarm.this["intact_elasticbeanstalk_prodconstructioncapacityapi_env_heal"] id = "INTACT_ElasticBeanstalk_Prodconstructioncapacityapi-env_Health_P1" }
import { to = module.cloudwatch.aws_cloudwatch_metric_alarm.this["intact_elasticbeanstalk_construction_capacity_api_dev_env_he"] id = "INTACT_ElasticBeanstalk_construction-capacity-api-dev-env_Health_P2" }
import { to = module.cloudwatch.aws_cloudwatch_metric_alarm.this["intact_lambda_construction_job_trigger_prod_errors_p1"] id = "INTACT_Lambda_Construction-job-trigger-prod_Errors_P1" }
import { to = module.cloudwatch.aws_cloudwatch_metric_alarm.this["intact_lambda_devconstructionlambdafunc_errors_p2"] id = "INTACT_Lambda_DevConstructionLambdaFunc_Errors_P2" }
import { to = module.cloudwatch.aws_cloudwatch_metric_alarm.this["intact_rds_ark_construction_db_dev_new_disk_p2_s1_90_per"] id = "INTACT_RDS_ark-construction-db-dev-new_Disk_P2_S1_90_Per" }
import { to = module.cloudwatch.aws_cloudwatch_metric_alarm.this["intact_rds_ark_construction_db_dev_cpuutilization_p2_s1_90_p"] id = "INTACT_RDS_ark-construction-db-dev_CPUUtilization_P2_S1_90_Per" }
import { to = module.cloudwatch.aws_cloudwatch_metric_alarm.this["intact_rds_ark_construction_db_dev_disk_p2_s1_90_per"] id = "INTACT_RDS_ark-construction-db-dev_Disk_P2_S1_90_Per" }
import { to = module.cloudwatch.aws_cloudwatch_metric_alarm.this["intact_rds_ark_construction_db_dev_new_cpuutilization_p2_s1_"] id = "INTACT_RDS_ark-construction-db-dev_new_CPUUtilization_P2_S1_90_Per" }
import { to = module.cloudwatch.aws_cloudwatch_metric_alarm.this["intact_rds_ark_construction_db_prod_new_cpuutilization_p1_s1"] id = "INTACT_RDS_ark-construction-db-prod-new_CPUUtilization_P1_S1_85_Per" }
import { to = module.cloudwatch.aws_cloudwatch_metric_alarm.this["intact_rds_ark_construction_db_prod_cpuutilization_p1_s1_85_"] id = "INTACT_RDS_ark-construction-db-prod_CPUUtilization_P1_S1_85_Per" }
import { to = module.cloudwatch.aws_cloudwatch_metric_alarm.this["intact_rds_constructioncapacityapi_db_dev_cpuutilization_p2_"] id = "INTACT_RDS_constructioncapacityapi-db-dev_CPUUtilization_P2_S1_90_Per" }
import { to = module.cloudwatch.aws_cloudwatch_metric_alarm.this["intact_rds_constructioncapacityapi_db_prod_cpuutilization_p1"] id = "INTACT_RDS_constructioncapacityapi-db-prod_CPUUtilization_P1_S1_85_Per" }
import { to = module.cloudwatch.aws_cloudwatch_metric_alarm.this["intact_vpn_intact_vpn_tunnelstate_p1"] id = "INTACT_VPN_Intact-vpn_TunnelState_P1" }
import { to = module.cloudwatch.aws_cloudwatch_metric_alarm.this["intact_ec2_construction_capacity_api_dev_env_high_cpu_utiliz"] id = "Intact-Ec2-construction-capacity-api-dev-env-high-CPU-Utilization" }
import { to = module.cloudwatch.aws_cloudwatch_metric_alarm.this["nacl_change"] id = "NACL_change" }
import { to = module.cloudwatch.aws_cloudwatch_metric_alarm.this["organizations_changes"] id = "Organizations changes" }
import { to = module.cloudwatch.aws_cloudwatch_metric_alarm.this["root_user_login"] id = "Root user login" }
import { to = module.cloudwatch.aws_cloudwatch_metric_alarm.this["route_table_changes"] id = "Route_table_changes" }
import { to = module.cloudwatch.aws_cloudwatch_metric_alarm.this["s3_bucket_policy_changes"] id = "S3_bucket_policy_changes" }
import { to = module.cloudwatch.aws_cloudwatch_metric_alarm.this["vpc_changes"] id = "VPC_changes" }
import { to = module.cloudwatch.aws_cloudwatch_metric_alarm.this["awseb_e_rf8gah3j8s_stack_awsebcloudwatchalarmhigh_jkg9lrb97x"] id = "awseb-e-rf8gah3j8s-stack-AWSEBCloudwatchAlarmHigh-JKG9LRB97XHY" }
import { to = module.cloudwatch.aws_cloudwatch_metric_alarm.this["awseb_e_rf8gah3j8s_stack_awsebcloudwatchalarmlow_roojy8h51r5"] id = "awseb-e-rf8gah3j8s-stack-AWSEBCloudwatchAlarmLow-ROOJY8H51R5Z" }
import { to = module.cloudwatch.aws_cloudwatch_metric_alarm.this["awseb_e_t2wrbbxesn_stack_awsebcloudwatchalarmhigh_cl8t8a7om6"] id = "awseb-e-t2wrbbxesn-stack-AWSEBCloudwatchAlarmHigh-CL8T8A7OM640" }
import { to = module.cloudwatch.aws_cloudwatch_metric_alarm.this["awseb_e_t2wrbbxesn_stack_awsebcloudwatchalarmlow_1hh5kpcy3rm"] id = "awseb-e-t2wrbbxesn-stack-AWSEBCloudwatchAlarmLow-1HH5KPCY3RMY9" }
import { to = module.cloudwatch.aws_cloudwatch_metric_alarm.this["consolelogin_authetication_failure"] id = "consolelogin_authetication_failure" }
import { to = module.cloudwatch.aws_cloudwatch_metric_alarm.this["consolelogin_without_mfa"] id = "consolelogin_without_MFA" }
import { to = module.cloudwatch.aws_cloudwatch_metric_alarm.this["customer_managed_keys_changes"] id = "customer_managed_keys_changes" }
import { to = module.cloudwatch.aws_cloudwatch_metric_alarm.this["network_gateways_changes"] id = "network_gateways_changes" }
import { to = module.cloudwatch.aws_cloudwatch_metric_alarm.this["security_group_change"] id = "security group change" }
import { to = module.cloudwatch.aws_cloudwatch_metric_alarm.this["unauthorized_apicall"] id = "unauthorized-apicall" }
import { to = module.sns.aws_sns_topic.this["all_topics_default"] id = "arn:aws:sns:us-east-2:401157580704:ALL_TOPICS_DEFAULT" }
import { to = module.sns.aws_sns_topic.this["cloudtrail_aws_configuration_changes"] id = "arn:aws:sns:us-east-2:401157580704:CloudTrail_AWS_Configuration_changes" }
import { to = module.sns.aws_sns_topic.this["cloud_formation_event_notification"] id = "arn:aws:sns:us-east-2:401157580704:Cloud_Formation_Event_Notification" }
import { to = module.sns.aws_sns_topic.this["config_configuration_changes"] id = "arn:aws:sns:us-east-2:401157580704:Config_configuration_changes" }
import { to = module.sns.aws_sns_topic.this["consolelogin_authentication_failures"] id = "arn:aws:sns:us-east-2:401157580704:Consolelogin_authentication_failures" }
import { to = module.sns.aws_sns_topic.this["consolelogin_without_mfa"] id = "arn:aws:sns:us-east-2:401157580704:Consolelogin_without_MFA" }
import { to = module.sns.aws_sns_topic.this["guardduty_alerts"] id = "arn:aws:sns:us-east-2:401157580704:GuardDuty-Alerts" }
import { to = module.sns.aws_sns_topic.this["iam_policy_changes"] id = "arn:aws:sns:us-east-2:401157580704:IAM_Policy_changes" }
import { to = module.sns.aws_sns_topic.this["intact_alb_awseb_awseb_15yb24hygypze_5xxs_p1"] id = "arn:aws:sns:us-east-2:401157580704:INTACT_ALB_awseb-AWSEB-15YB24HYGYPZE_5XXs_P1" }
import { to = module.sns.aws_sns_topic.this["intact_alb_awseb_awseb_zo7qrx88vt24_5xxs_p2"] id = "arn:aws:sns:us-east-2:401157580704:INTACT_ALB_awseb-AWSEB-ZO7QRX88VT24_5XXs_P2" }
import { to = module.sns.aws_sns_topic.this["intact_apigateway_construction_capacity_api_sapiens_4xxerror"] id = "arn:aws:sns:us-east-2:401157580704:INTACT_APIgateway_construction-capacity-api-Sapiens_4xxError_P2" }
import { to = module.sns.aws_sns_topic.this["intact_apigateway_construction_capacity_api_sapiens_5xxerror"] id = "arn:aws:sns:us-east-2:401157580704:INTACT_APIgateway_construction-capacity-api-Sapiens_5xxError_P2" }
import { to = module.sns.aws_sns_topic.this["intact_apigateway_construction_capacity_api_prod_sapiens_4xx"] id = "arn:aws:sns:us-east-2:401157580704:INTACT_APIgateway_construction-capacity-api-prod-Sapiens_4xxError_P1" }
import { to = module.sns.aws_sns_topic.this["intact_apigateway_construction_capacity_api_prod_sapiens_5xx"] id = "arn:aws:sns:us-east-2:401157580704:INTACT_APIgateway_construction-capacity-api-prod-Sapiens_5xxError_P1" }
import { to = module.sns.aws_sns_topic.this["intact_ec2_availability_p1"] id = "arn:aws:sns:us-east-2:401157580704:INTACT_EC2_Availability_P1" }
import { to = module.sns.aws_sns_topic.this["intact_ec2_powerbi_desktop_new_cpuutilization_psteam"] id = "arn:aws:sns:us-east-2:401157580704:INTACT_EC2_Powerbi-Desktop-new_CPUUtilization_PSteam" }
import { to = module.sns.aws_sns_topic.this["intact_ec2_powerbi_desktop_prod_new_cpuutilization_psteam"] id = "arn:aws:sns:us-east-2:401157580704:INTACT_EC2_Powerbi-Desktop-prod-new_CPUUtilization_PSteam" }
import { to = module.sns.aws_sns_topic.this["intact_elasticbeanstalk_prodconstructioncapacityapi_env_heal"] id = "arn:aws:sns:us-east-2:401157580704:INTACT_ElasticBeanstalk_Prodconstructioncapacityapi-env_Health_P2" }
import { to = module.sns.aws_sns_topic.this["intact_elasticbeanstalk_construction_capacity_api_dev_env_he"] id = "arn:aws:sns:us-east-2:401157580704:INTACT_ElasticBeanstalk_construction-capacity-api-dev-env_Health_P2" }
import { to = module.sns.aws_sns_topic.this["intact_glue_job_state_change"] id = "arn:aws:sns:us-east-2:401157580704:INTACT_GLUE_job_state_change" }
import { to = module.sns.aws_sns_topic.this["intact_iam_changes_p1"] id = "arn:aws:sns:us-east-2:401157580704:INTACT_IAM_changes_P1" }
import { to = module.sns.aws_sns_topic.this["intact_lambda_construction_job_trigger_prod_errors_p1"] id = "arn:aws:sns:us-east-2:401157580704:INTACT_Lambda_Construction-job-trigger-prod_Errors_P1" }
import { to = module.sns.aws_sns_topic.this["intact_lambda_devconstructionlambdafunc_errors_p2"] id = "arn:aws:sns:us-east-2:401157580704:INTACT_Lambda_DevConstructionLambdaFunc_Errors_P2" }
import { to = module.sns.aws_sns_topic.this["intact_rds_availability"] id = "arn:aws:sns:us-east-2:401157580704:INTACT_RDS_Availability" }
import { to = module.sns.aws_sns_topic.this["intact_rds_ark_construction_db_dev_cpuutilization_psteam"] id = "arn:aws:sns:us-east-2:401157580704:INTACT_RDS_ark-construction-db-dev_CPUUtilization_PSteam" }
import { to = module.sns.aws_sns_topic.this["intact_rds_ark_construction_db_dev_disk_p2"] id = "arn:aws:sns:us-east-2:401157580704:INTACT_RDS_ark-construction-db-dev_Disk_P2" }
import { to = module.sns.aws_sns_topic.this["intact_rds_ark_construction_db_prod_cpuutilization_psteam"] id = "arn:aws:sns:us-east-2:401157580704:INTACT_RDS_ark-construction-db-prod_CPUUtilization_PSteam" }
import { to = module.sns.aws_sns_topic.this["intact_rds_constructioncapacityapi_db_dev_cpuutilization_pst"] id = "arn:aws:sns:us-east-2:401157580704:INTACT_RDS_constructioncapacityapi-db-dev_CPUUtilization_PSteam" }
import { to = module.sns.aws_sns_topic.this["intact_rds_constructioncapacityapi_db_prod_cpuutilization_ps"] id = "arn:aws:sns:us-east-2:401157580704:INTACT_RDS_constructioncapacityapi-db-prod_CPUUtilization_PSteam" }
import { to = module.sns.aws_sns_topic.this["intact_ssm_powerbi_desktop_new_patching"] id = "arn:aws:sns:us-east-2:401157580704:INTACT_SSM-Powerbi-Desktop-new-Patching" }
import { to = module.sns.aws_sns_topic.this["intact_security_hub_summary"] id = "arn:aws:sns:us-east-2:401157580704:INTACT_Security_hub_summary" }
import { to = module.sns.aws_sns_topic.this["intact_vpn_intact_vpn_tunnelstate_p1"] id = "arn:aws:sns:us-east-2:401157580704:INTACT_VPN_Intact-vpn_TunnelState_P1" }
import { to = module.sns.aws_sns_topic.this["intact_alerts"] id = "arn:aws:sns:us-east-2:401157580704:Intact-Alerts" }
import { to = module.sns.aws_sns_topic.this["intact_console_login"] id = "arn:aws:sns:us-east-2:401157580704:Intact_console_login" }
import { to = module.sns.aws_sns_topic.this["nacl_changes"] id = "arn:aws:sns:us-east-2:401157580704:NACL_changes" }
import { to = module.sns.aws_sns_topic.this["root_user_login_intact"] id = "arn:aws:sns:us-east-2:401157580704:Root_user_login_intact" }
import { to = module.sns.aws_sns_topic.this["routetablechangesalerts"] id = "arn:aws:sns:us-east-2:401157580704:RouteTableChangesAlerts" }
import { to = module.sns.aws_sns_topic.this["route_table_changes"] id = "arn:aws:sns:us-east-2:401157580704:Route_table_changes" }
import { to = module.sns.aws_sns_topic.this["s3_event_notification"] id = "arn:aws:sns:us-east-2:401157580704:S3_Event_Notification" }
import { to = module.sns.aws_sns_topic.this["s3_bucket_policy_changes"] id = "arn:aws:sns:us-east-2:401157580704:S3_bucket_policy_changes" }
import { to = module.sns.aws_sns_topic.this["securityhubalerts"] id = "arn:aws:sns:us-east-2:401157580704:SecurityHubAlerts" }
import { to = module.sns.aws_sns_topic.this["vpc_changes"] id = "arn:aws:sns:us-east-2:401157580704:VPC_changes" }
import { to = module.sns.aws_sns_topic.this["weely_resources_report"] id = "arn:aws:sns:us-east-2:401157580704:Weely_Resources-Report" }
import { to = module.sns.aws_sns_topic.this["aws_cloudtrail_logs_snsnotificationdelivery"] id = "arn:aws:sns:us-east-2:401157580704:aws-cloudtrail-logs-snsnotificationdelivery" }
import { to = module.sns.aws_sns_topic.this["customer_managed_keys_changes"] id = "arn:aws:sns:us-east-2:401157580704:customer_managed_keys_changes" }
import { to = module.sns.aws_sns_topic.this["network_gateways_modified"] id = "arn:aws:sns:us-east-2:401157580704:network_gateways_modified" }
import { to = module.sns.aws_sns_topic.this["rds_security_group_events_subscription"] id = "arn:aws:sns:us-east-2:401157580704:rds-security-group-events-subscription" }
import { to = module.sns.aws_sns_topic.this["security_group_change"] id = "arn:aws:sns:us-east-2:401157580704:security_group_change" }
import { to = module.sns.aws_sns_topic.this["test_topic_jsm"] id = "arn:aws:sns:us-east-2:401157580704:test-topic-jsm" }
import { to = module.sns.aws_sns_topic.this["unauthorized_apicall"] id = "arn:aws:sns:us-east-2:401157580704:unauthorized_apicall" }
import { to = module.lambda.aws_lambda_function.this["weekly_resource_inventory"] id = "Weekly_Resource_Inventory" }
import { to = module.lambda.aws_lambda_function.this["secretsmanager_key_rotation_lambda"] id = "Secretsmanager-key-rotation-lambda" }
import { to = module.lambda.aws_lambda_function.this["devconstructionlambdafunc"] id = "DevConstructionLambdaFunc" }
import { to = module.lambda.aws_lambda_function.this["aws_lambda_apigateway"] id = "AWS_Lambda-APIGateway" }
import { to = module.lambda.aws_lambda_function.this["securityhubprocessor"] id = "SecurityHubProcessor" }
import { to = module.lambda.aws_lambda_function.this["aws_glue_state_custom_email"] id = "AWS-Glue-state-custom-email" }
import { to = module.lambda.aws_lambda_function.this["sendsecurityhubsummaryemail"] id = "SendSecurityHubSummaryEmail" }
import { to = module.lambda.aws_lambda_function.this["consolelogin_authentication_failures"] id = "Consolelogin_authentication_failures" }
import { to = module.lambda.aws_lambda_function.this["custom_email_for_ec2_and_rds"] id = "Custom-email-for-EC2-and-RDS" }
import { to = module.lambda.aws_lambda_function.this["intact_security_hub_finding_custominsightsfunction_frvvufetz"] id = "intact-security-hub-finding-CustomInsightsFunction-FrvVUFetZhGd" }
import { to = module.lambda.aws_lambda_function.this["construction_job_trigger_prod"] id = "Construction-job-trigger-prod" }
import { to = module.lambda.aws_lambda_function.this["sns_delivery_status_logging"] id = "SNS_Delivery_Status_Logging" }
import { to = module.api_gateway.aws_api_gateway_rest_api.this["construction_capacity_api"] id = "56w6okmgia" }
import { to = module.api_gateway.aws_api_gateway_rest_api.this["construction_capacity_api_prod"] id = "uex978iquh" }
import { to = module.secretsmanager.aws_secretsmanager_secret.this["powerbi_dev"] id = "arn:aws:secretsmanager:us-east-2:401157580704:secret:Powerbi-dev-4L4KAG" }
import { to = module.secretsmanager.aws_secretsmanager_secret.this["powerbi_prod"] id = "arn:aws:secretsmanager:us-east-2:401157580704:secret:Powerbi-prod-FiQgaV" }
import { to = module.secretsmanager.aws_secretsmanager_secret.this["capacity_api_dev"] id = "arn:aws:secretsmanager:us-east-2:401157580704:secret:Capacity-api-dev-JL6UZ8" }
import { to = module.secretsmanager.aws_secretsmanager_secret.this["constructioncapacityapi_db_prod"] id = "arn:aws:secretsmanager:us-east-2:401157580704:secret:constructioncapacityapi-db-prod-Xol0BV" }
import { to = module.secretsmanager.aws_secretsmanager_secret.this["ark_construction_db_dev"] id = "arn:aws:secretsmanager:us-east-2:401157580704:secret:ark-construction-db-dev-wRYQtB" }
import { to = module.secretsmanager.aws_secretsmanager_secret.this["ark_construction_db_prod"] id = "arn:aws:secretsmanager:us-east-2:401157580704:secret:ark-construction-db-prod-nAB2D6" }
import { to = module.secretsmanager.aws_secretsmanager_secret.this["pwerbi_desktop_new"] id = "arn:aws:secretsmanager:us-east-2:401157580704:secret:pwerbi-Desktop-new-LOPTnE" }
import { to = module.secretsmanager.aws_secretsmanager_secret.this["powerbi_dev_gateway_key"] id = "arn:aws:secretsmanager:us-east-2:401157580704:secret:powerbi-dev-gateway-key-Ziu85P" }
import { to = module.secretsmanager.aws_secretsmanager_secret.this["dev_construction_postgresql"] id = "arn:aws:secretsmanager:us-east-2:401157580704:secret:dev/construction/postgresql-ssS8AN" }
import { to = module.secretsmanager.aws_secretsmanager_secret.this["prod_construction_postgresql"] id = "arn:aws:secretsmanager:us-east-2:401157580704:secret:prod/construction/postgresql-1fsFGI" }
import { to = module.secretsmanager.aws_secretsmanager_secret.this["sapiens_data_rpl_db_dev"] id = "arn:aws:secretsmanager:us-east-2:401157580704:secret:sapiens-data-rpl-db-dev-rlW5eX" }
import { to = module.secretsmanager.aws_secretsmanager_secret.this["sapiens_data_rpl_db_prod"] id = "arn:aws:secretsmanager:us-east-2:401157580704:secret:sapiens-data-rpl-db-prod-yypQeu" }
