locals {
  security_groups = {
  "prod_vpc_internal_traffic": {
    "id": "sg-0a3e289da76de0353",
    "name": "Prod-vpc-internal-traffic",
    "description": "Allow internal traffic in Prod-vpc",
    "vpc_id": "vpc-0773253bc4daca414"
  },
  "linux_bastion": {
    "id": "sg-0596e9366f2299407",
    "name": "Linux-bastion",
    "description": "launch-wizard-1 created 2021-12-30T11:28:02.811+05:30",
    "vpc_id": "vpc-056be321b2abea9e8"
  },
  "sapiens_data_rpl_db_dev_sg": {
    "id": "sg-0be9a2b7d42034fac",
    "name": "sapiens-data-rpl-db-dev-sg",
    "description": "SG for sapiens-data-rpl-db-dev",
    "vpc_id": "vpc-056be321b2abea9e8"
  },
  "constructioncapacityapi_ebs_security": {
    "id": "sg-0997987b6834efa73",
    "name": "constructioncapacityapi-ebs-security",
    "description": "constructioncapacityapi-ebs-security",
    "vpc_id": "vpc-056be321b2abea9e8"
  },
  "sapiens_data_rpl_db_prod_sg": {
    "id": "sg-0897b83200c529324",
    "name": "sapiens-data-rpl-db-prod-sg",
    "description": "SG for sapiens-data-rpl-db-prod",
    "vpc_id": "vpc-0773253bc4daca414"
  },
  "microsoft_windows_server_2019_base_2022_02_10_autogenbyawsmp": {
    "id": "sg-0da6cc2bc59441b15",
    "name": "Microsoft Windows Server 2019 Base-2022-02-10-AutogenByAWSMP-2",
    "description": "This security group was generated by AWS Marketplace and is based on recommended settings for Microsoft Windows Server 2019 Base version 2022.02.10 provided by Amazon Web Services",
    "vpc_id": "vpc-056be321b2abea9e8"
  },
  "awseb_e_t2wrbbxesn_stack_awsebsecuritygroup_17z98mkyxwdoa": {
    "id": "sg-0985bc300f673015a",
    "name": "awseb-e-t2wrbbxesn-stack-AWSEBSecurityGroup-17Z98MKYXWDOA",
    "description": "VPC Security Group",
    "vpc_id": "vpc-0773253bc4daca414"
  },
  "default": {
    "id": "sg-080f28d7569af1b80",
    "name": "default",
    "description": "default VPC security group",
    "vpc_id": "vpc-0773253bc4daca414"
  },
  "constructioncapacity_rds_dev": {
    "id": "sg-0e9b70067d7334c56",
    "name": "constructioncapacity-rds-dev",
    "description": "Created by RDS management console",
    "vpc_id": "vpc-056be321b2abea9e8"
  },
  "intact_dev_glue_sg": {
    "id": "sg-04815e9ede6f75abc",
    "name": "intact-dev-glue-sg",
    "description": "intact-dev-glue-sg",
    "vpc_id": "vpc-056be321b2abea9e8"
  },
  "intact_prod_glue_sg": {
    "id": "sg-0ae915b71b9ca13b5",
    "name": "intact-prod-glue-sg",
    "description": "Allow Traffic to security group",
    "vpc_id": "vpc-0773253bc4daca414"
  },
  "construction_job_trigger_prod_lambda_sg": {
    "id": "sg-0ed15004f60fe5ddf",
    "name": "Construction-job-trigger-prod-lambda-SG",
    "description": "This sg is used by Construction-job-trigger-prod-lambda",
    "vpc_id": "vpc-0773253bc4daca414"
  },
  "bastion_windows": {
    "id": "sg-0df12569ecaa6569a",
    "name": "bastion-windows",
    "description": "launch-wizard-1 created 2021-12-29T13:43:07.321+05:30",
    "vpc_id": "vpc-056be321b2abea9e8"
  },
  "intact_allow_traffic_to_prod_vpc": {
    "id": "sg-08389ac9ffe6a06f7",
    "name": "intact-allow-traffic-to-prod-vpc",
    "description": "Allows Traffic from Intact environment",
    "vpc_id": "vpc-0773253bc4daca414"
  },
  "constructioncapacity_rds_prod": {
    "id": "sg-062b09810708db6ef",
    "name": "constructioncapacity-rds-prod",
    "description": "Created by RDS management console",
    "vpc_id": "vpc-0773253bc4daca414"
  },
  "linux_bastion_prod_vpc": {
    "id": "sg-0374bef6b6effcd1c",
    "name": "Linux-bastion-prod-vpc",
    "description": "Allow SSH access to Linux bastion host in Prod VPC",
    "vpc_id": "vpc-0773253bc4daca414"
  },
  "awseb_e_rf8gah3j8s_stack_awsebsecuritygroup_53u52xnkral6": {
    "id": "sg-0a91845af00af000d",
    "name": "awseb-e-rf8gah3j8s-stack-AWSEBSecurityGroup-53U52XNKRAL6",
    "description": "VPC Security Group",
    "vpc_id": "vpc-056be321b2abea9e8"
  },
  "awseb_e_rf8gah3j8s_stack_awsebloadbalancersecuritygroup_1kbh": {
    "id": "sg-0721a3e0f69333439",
    "name": "awseb-e-rf8gah3j8s-stack-AWSEBLoadBalancerSecurityGroup-1KBHTW9N3VJH2",
    "description": "Load Balancer Security Group",
    "vpc_id": "vpc-056be321b2abea9e8"
  },
  "awseb_e_t2wrbbxesn_stack_awsebloadbalancersecuritygroup_1sz1": {
    "id": "sg-0f5616250eb4610eb",
    "name": "awseb-e-t2wrbbxesn-stack-AWSEBLoadBalancerSecurityGroup-1SZ19IEBCX5Q8",
    "description": "Load Balancer Security Group",
    "vpc_id": "vpc-0773253bc4daca414"
  }
}
  ingress_rules = {
  "prod_vpc_internal_traffic_0": {
    "sg": "prod_vpc_internal_traffic",
    "protocol": "-1",
    "from_port": null,
    "to_port": null,
    "cidr_blocks": [
      "10.1.0.0/16",
      "10.2.0.0/16"
    ],
    "ipv6_cidr_blocks": [],
    "source_sgs": []
  },
  "linux_bastion_0": {
    "sg": "linux_bastion",
    "protocol": "tcp",
    "from_port": 22,
    "to_port": 22,
    "cidr_blocks": [
      "10.2.0.0/16",
      "205.134.132.1/32"
    ],
    "ipv6_cidr_blocks": [],
    "source_sgs": []
  },
  "linux_bastion_1": {
    "sg": "linux_bastion",
    "protocol": "icmp",
    "from_port": -1,
    "to_port": -1,
    "cidr_blocks": [
      "10.2.0.0/16"
    ],
    "ipv6_cidr_blocks": [],
    "source_sgs": []
  },
  "sapiens_data_rpl_db_dev_sg_0": {
    "sg": "sapiens_data_rpl_db_dev_sg",
    "protocol": "tcp",
    "from_port": 5432,
    "to_port": 5432,
    "cidr_blocks": [
      "10.2.0.0/16",
      "10.0.0.0/16",
      "10.93.151.110/32"
    ],
    "ipv6_cidr_blocks": [],
    "source_sgs": []
  },
  "constructioncapacityapi_ebs_security_0": {
    "sg": "constructioncapacityapi_ebs_security",
    "protocol": "tcp",
    "from_port": 80,
    "to_port": 80,
    "cidr_blocks": [
      "10.0.0.0/16"
    ],
    "ipv6_cidr_blocks": [],
    "source_sgs": []
  },
  "constructioncapacityapi_ebs_security_1": {
    "sg": "constructioncapacityapi_ebs_security",
    "protocol": "tcp",
    "from_port": 443,
    "to_port": 443,
    "cidr_blocks": [
      "10.0.0.0/16"
    ],
    "ipv6_cidr_blocks": [],
    "source_sgs": []
  },
  "sapiens_data_rpl_db_prod_sg_0": {
    "sg": "sapiens_data_rpl_db_prod_sg",
    "protocol": "tcp",
    "from_port": 5432,
    "to_port": 5432,
    "cidr_blocks": [
      "10.93.151.110/32",
      "10.1.0.0/16",
      "10.2.0.0/16"
    ],
    "ipv6_cidr_blocks": [],
    "source_sgs": []
  },
  "microsoft_windows_server_2019_base_2022_02_10_autogenbyawsmp_0": {
    "sg": "microsoft_windows_server_2019_base_2022_02_10_autogenbyawsmp",
    "protocol": "tcp",
    "from_port": 5432,
    "to_port": 5432,
    "cidr_blocks": [
      "10.0.0.0/16"
    ],
    "ipv6_cidr_blocks": [],
    "source_sgs": []
  },
  "microsoft_windows_server_2019_base_2022_02_10_autogenbyawsmp_1": {
    "sg": "microsoft_windows_server_2019_base_2022_02_10_autogenbyawsmp",
    "protocol": "-1",
    "from_port": null,
    "to_port": null,
    "cidr_blocks": [
      "10.2.0.0/16"
    ],
    "ipv6_cidr_blocks": [],
    "source_sgs": []
  },
  "awseb_e_t2wrbbxesn_stack_awsebsecuritygroup_17z98mkyxwdoa_0": {
    "sg": "awseb_e_t2wrbbxesn_stack_awsebsecuritygroup_17z98mkyxwdoa",
    "protocol": "tcp",
    "from_port": 80,
    "to_port": 80,
    "cidr_blocks": [
      "10.1.0.0/16"
    ],
    "ipv6_cidr_blocks": [],
    "source_sgs": [
      "sg-0f5616250eb4610eb"
    ]
  },
  "awseb_e_t2wrbbxesn_stack_awsebsecuritygroup_17z98mkyxwdoa_1": {
    "sg": "awseb_e_t2wrbbxesn_stack_awsebsecuritygroup_17z98mkyxwdoa",
    "protocol": "tcp",
    "from_port": 443,
    "to_port": 443,
    "cidr_blocks": [
      "10.1.0.0/16"
    ],
    "ipv6_cidr_blocks": [],
    "source_sgs": [
      "sg-0f5616250eb4610eb"
    ]
  },
  "microsoft_windows_server_2019_base_2022_02_10_autogenbyawsmp_2": {
    "sg": "microsoft_windows_server_2019_base_2022_02_10_autogenbyawsmp",
    "protocol": "tcp",
    "from_port": 3389,
    "to_port": 3389,
    "cidr_blocks": [
      "10.0.0.0/16"
    ],
    "ipv6_cidr_blocks": [],
    "source_sgs": []
  },
  "constructioncapacity_rds_dev_0": {
    "sg": "constructioncapacity_rds_dev",
    "protocol": "tcp",
    "from_port": 5432,
    "to_port": 5432,
    "cidr_blocks": [
      "10.0.0.0/16",
      "10.2.0.0/16"
    ],
    "ipv6_cidr_blocks": [],
    "source_sgs": []
  },
  "intact_dev_glue_sg_0": {
    "sg": "intact_dev_glue_sg",
    "protocol": "tcp",
    "from_port": 5432,
    "to_port": 5432,
    "cidr_blocks": [
      "10.0.0.0/16"
    ],
    "ipv6_cidr_blocks": [],
    "source_sgs": []
  },
  "intact_dev_glue_sg_1": {
    "sg": "intact_dev_glue_sg",
    "protocol": "-1",
    "from_port": null,
    "to_port": null,
    "cidr_blocks": [],
    "ipv6_cidr_blocks": [],
    "source_sgs": [
      "sg-04815e9ede6f75abc"
    ]
  },
  "intact_prod_glue_sg_0": {
    "sg": "intact_prod_glue_sg",
    "protocol": "tcp",
    "from_port": 5432,
    "to_port": 5432,
    "cidr_blocks": [
      "10.1.0.0/16"
    ],
    "ipv6_cidr_blocks": [],
    "source_sgs": []
  },
  "intact_prod_glue_sg_1": {
    "sg": "intact_prod_glue_sg",
    "protocol": "-1",
    "from_port": null,
    "to_port": null,
    "cidr_blocks": [],
    "ipv6_cidr_blocks": [],
    "source_sgs": [
      "sg-0ae915b71b9ca13b5"
    ]
  },
  "bastion_windows_0": {
    "sg": "bastion_windows",
    "protocol": "tcp",
    "from_port": 3389,
    "to_port": 3389,
    "cidr_blocks": [
      "10.0.0.0/16"
    ],
    "ipv6_cidr_blocks": [],
    "source_sgs": []
  },
  "intact_allow_traffic_to_prod_vpc_0": {
    "sg": "intact_allow_traffic_to_prod_vpc",
    "protocol": "tcp",
    "from_port": 22,
    "to_port": 22,
    "cidr_blocks": [
      "208.127.105.118/32",
      "208.127.247.230/32",
      "205.134.132.1/32",
      "208.127.227.178/32",
      "165.1.146.64/32",
      "205.134.158.2/32",
      "208.127.74.80/32",
      "208.127.105.123/32",
      "137.83.222.122/32",
      "208.127.227.157/32",
      "137.83.222.109/32",
      "208.127.227.158/32",
      "208.127.108.168/32"
    ],
    "ipv6_cidr_blocks": [],
    "source_sgs": []
  },
  "intact_allow_traffic_to_prod_vpc_1": {
    "sg": "intact_allow_traffic_to_prod_vpc",
    "protocol": "tcp",
    "from_port": 3389,
    "to_port": 3389,
    "cidr_blocks": [
      "10.2.0.0/16"
    ],
    "ipv6_cidr_blocks": [],
    "source_sgs": []
  },
  "constructioncapacity_rds_prod_0": {
    "sg": "constructioncapacity_rds_prod",
    "protocol": "tcp",
    "from_port": 0,
    "to_port": 65535,
    "cidr_blocks": [],
    "ipv6_cidr_blocks": [],
    "source_sgs": [
      "sg-062b09810708db6ef"
    ]
  },
  "constructioncapacity_rds_prod_1": {
    "sg": "constructioncapacity_rds_prod",
    "protocol": "tcp",
    "from_port": 5432,
    "to_port": 5432,
    "cidr_blocks": [
      "10.0.0.105/32",
      "10.1.0.0/16"
    ],
    "ipv6_cidr_blocks": [],
    "source_sgs": [
      "sg-0596e9366f2299407",
      "sg-0da6cc2bc59441b15",
      "sg-0105905ad93a56e72",
      "sg-0985bc300f673015a",
      "sg-0374bef6b6effcd1c"
    ]
  },
  "linux_bastion_prod_vpc_0": {
    "sg": "linux_bastion_prod_vpc",
    "protocol": "tcp",
    "from_port": 22,
    "to_port": 22,
    "cidr_blocks": [
      "10.2.0.0/16"
    ],
    "ipv6_cidr_blocks": [],
    "source_sgs": []
  },
  "linux_bastion_prod_vpc_1": {
    "sg": "linux_bastion_prod_vpc",
    "protocol": "tcp",
    "from_port": 3389,
    "to_port": 3389,
    "cidr_blocks": [
      "10.2.0.0/16"
    ],
    "ipv6_cidr_blocks": [],
    "source_sgs": []
  },
  "awseb_e_rf8gah3j8s_stack_awsebsecuritygroup_53u52xnkral6_0": {
    "sg": "awseb_e_rf8gah3j8s_stack_awsebsecuritygroup_53u52xnkral6",
    "protocol": "tcp",
    "from_port": 80,
    "to_port": 80,
    "cidr_blocks": [
      "10.0.0.0/16"
    ],
    "ipv6_cidr_blocks": [],
    "source_sgs": [
      "sg-0721a3e0f69333439"
    ]
  },
  "awseb_e_rf8gah3j8s_stack_awsebsecuritygroup_53u52xnkral6_1": {
    "sg": "awseb_e_rf8gah3j8s_stack_awsebsecuritygroup_53u52xnkral6",
    "protocol": "tcp",
    "from_port": 22,
    "to_port": 22,
    "cidr_blocks": [
      "10.0.0.0/16"
    ],
    "ipv6_cidr_blocks": [],
    "source_sgs": []
  },
  "awseb_e_rf8gah3j8s_stack_awsebsecuritygroup_53u52xnkral6_2": {
    "sg": "awseb_e_rf8gah3j8s_stack_awsebsecuritygroup_53u52xnkral6",
    "protocol": "tcp",
    "from_port": 443,
    "to_port": 443,
    "cidr_blocks": [
      "10.0.0.0/16"
    ],
    "ipv6_cidr_blocks": [],
    "source_sgs": [
      "sg-0721a3e0f69333439"
    ]
  },
  "awseb_e_rf8gah3j8s_stack_awsebloadbalancersecuritygroup_1kbh_0": {
    "sg": "awseb_e_rf8gah3j8s_stack_awsebloadbalancersecuritygroup_1kbh",
    "protocol": "tcp",
    "from_port": 80,
    "to_port": 80,
    "cidr_blocks": [
      "10.0.0.0/16"
    ],
    "ipv6_cidr_blocks": [],
    "source_sgs": []
  },
  "awseb_e_rf8gah3j8s_stack_awsebloadbalancersecuritygroup_1kbh_1": {
    "sg": "awseb_e_rf8gah3j8s_stack_awsebloadbalancersecuritygroup_1kbh",
    "protocol": "tcp",
    "from_port": 443,
    "to_port": 443,
    "cidr_blocks": [
      "10.0.0.0/16"
    ],
    "ipv6_cidr_blocks": [],
    "source_sgs": []
  },
  "awseb_e_t2wrbbxesn_stack_awsebloadbalancersecuritygroup_1sz1_0": {
    "sg": "awseb_e_t2wrbbxesn_stack_awsebloadbalancersecuritygroup_1sz1",
    "protocol": "tcp",
    "from_port": 80,
    "to_port": 80,
    "cidr_blocks": [
      "10.1.0.0/16"
    ],
    "ipv6_cidr_blocks": [],
    "source_sgs": []
  },
  "awseb_e_t2wrbbxesn_stack_awsebloadbalancersecuritygroup_1sz1_1": {
    "sg": "awseb_e_t2wrbbxesn_stack_awsebloadbalancersecuritygroup_1sz1",
    "protocol": "tcp",
    "from_port": 443,
    "to_port": 443,
    "cidr_blocks": [
      "10.1.0.0/16"
    ],
    "ipv6_cidr_blocks": [],
    "source_sgs": []
  }
}
  egress_rules = {
  "prod_vpc_internal_traffic_0": {
    "sg": "prod_vpc_internal_traffic",
    "protocol": "-1",
    "from_port": null,
    "to_port": null,
    "cidr_blocks": [
      "0.0.0.0/0"
    ],
    "ipv6_cidr_blocks": [],
    "dest_sgs": []
  },
  "linux_bastion_0": {
    "sg": "linux_bastion",
    "protocol": "-1",
    "from_port": null,
    "to_port": null,
    "cidr_blocks": [
      "0.0.0.0/0"
    ],
    "ipv6_cidr_blocks": [],
    "dest_sgs": []
  },
  "sapiens_data_rpl_db_dev_sg_0": {
    "sg": "sapiens_data_rpl_db_dev_sg",
    "protocol": "-1",
    "from_port": null,
    "to_port": null,
    "cidr_blocks": [
      "0.0.0.0/0"
    ],
    "ipv6_cidr_blocks": [],
    "dest_sgs": []
  },
  "constructioncapacityapi_ebs_security_0": {
    "sg": "constructioncapacityapi_ebs_security",
    "protocol": "-1",
    "from_port": null,
    "to_port": null,
    "cidr_blocks": [
      "0.0.0.0/0"
    ],
    "ipv6_cidr_blocks": [],
    "dest_sgs": []
  },
  "sapiens_data_rpl_db_prod_sg_0": {
    "sg": "sapiens_data_rpl_db_prod_sg",
    "protocol": "-1",
    "from_port": null,
    "to_port": null,
    "cidr_blocks": [
      "0.0.0.0/0"
    ],
    "ipv6_cidr_blocks": [],
    "dest_sgs": []
  },
  "microsoft_windows_server_2019_base_2022_02_10_autogenbyawsmp_0": {
    "sg": "microsoft_windows_server_2019_base_2022_02_10_autogenbyawsmp",
    "protocol": "-1",
    "from_port": null,
    "to_port": null,
    "cidr_blocks": [
      "0.0.0.0/0"
    ],
    "ipv6_cidr_blocks": [],
    "dest_sgs": []
  },
  "awseb_e_t2wrbbxesn_stack_awsebsecuritygroup_17z98mkyxwdoa_0": {
    "sg": "awseb_e_t2wrbbxesn_stack_awsebsecuritygroup_17z98mkyxwdoa",
    "protocol": "-1",
    "from_port": null,
    "to_port": null,
    "cidr_blocks": [
      "0.0.0.0/0"
    ],
    "ipv6_cidr_blocks": [],
    "dest_sgs": []
  },
  "constructioncapacity_rds_dev_0": {
    "sg": "constructioncapacity_rds_dev",
    "protocol": "-1",
    "from_port": null,
    "to_port": null,
    "cidr_blocks": [
      "0.0.0.0/0"
    ],
    "ipv6_cidr_blocks": [],
    "dest_sgs": []
  },
  "intact_dev_glue_sg_0": {
    "sg": "intact_dev_glue_sg",
    "protocol": "-1",
    "from_port": null,
    "to_port": null,
    "cidr_blocks": [
      "0.0.0.0/0"
    ],
    "ipv6_cidr_blocks": [],
    "dest_sgs": []
  },
  "intact_prod_glue_sg_0": {
    "sg": "intact_prod_glue_sg",
    "protocol": "-1",
    "from_port": null,
    "to_port": null,
    "cidr_blocks": [
      "0.0.0.0/0"
    ],
    "ipv6_cidr_blocks": [],
    "dest_sgs": []
  },
  "construction_job_trigger_prod_lambda_sg_0": {
    "sg": "construction_job_trigger_prod_lambda_sg",
    "protocol": "-1",
    "from_port": null,
    "to_port": null,
    "cidr_blocks": [
      "0.0.0.0/0"
    ],
    "ipv6_cidr_blocks": [],
    "dest_sgs": []
  },
  "bastion_windows_0": {
    "sg": "bastion_windows",
    "protocol": "-1",
    "from_port": null,
    "to_port": null,
    "cidr_blocks": [
      "0.0.0.0/0"
    ],
    "ipv6_cidr_blocks": [],
    "dest_sgs": []
  },
  "intact_allow_traffic_to_prod_vpc_0": {
    "sg": "intact_allow_traffic_to_prod_vpc",
    "protocol": "-1",
    "from_port": null,
    "to_port": null,
    "cidr_blocks": [
      "0.0.0.0/0"
    ],
    "ipv6_cidr_blocks": [],
    "dest_sgs": []
  },
  "constructioncapacity_rds_prod_0": {
    "sg": "constructioncapacity_rds_prod",
    "protocol": "-1",
    "from_port": null,
    "to_port": null,
    "cidr_blocks": [
      "0.0.0.0/0"
    ],
    "ipv6_cidr_blocks": [],
    "dest_sgs": []
  },
  "linux_bastion_prod_vpc_0": {
    "sg": "linux_bastion_prod_vpc",
    "protocol": "-1",
    "from_port": null,
    "to_port": null,
    "cidr_blocks": [
      "0.0.0.0/0"
    ],
    "ipv6_cidr_blocks": [],
    "dest_sgs": []
  },
  "awseb_e_rf8gah3j8s_stack_awsebsecuritygroup_53u52xnkral6_0": {
    "sg": "awseb_e_rf8gah3j8s_stack_awsebsecuritygroup_53u52xnkral6",
    "protocol": "-1",
    "from_port": null,
    "to_port": null,
    "cidr_blocks": [
      "0.0.0.0/0"
    ],
    "ipv6_cidr_blocks": [],
    "dest_sgs": []
  },
  "awseb_e_rf8gah3j8s_stack_awsebloadbalancersecuritygroup_1kbh_0": {
    "sg": "awseb_e_rf8gah3j8s_stack_awsebloadbalancersecuritygroup_1kbh",
    "protocol": "tcp",
    "from_port": 80,
    "to_port": 80,
    "cidr_blocks": [
      "0.0.0.0/0"
    ],
    "ipv6_cidr_blocks": [],
    "dest_sgs": []
  },
  "awseb_e_rf8gah3j8s_stack_awsebloadbalancersecuritygroup_1kbh_1": {
    "sg": "awseb_e_rf8gah3j8s_stack_awsebloadbalancersecuritygroup_1kbh",
    "protocol": "tcp",
    "from_port": 443,
    "to_port": 443,
    "cidr_blocks": [
      "0.0.0.0/0"
    ],
    "ipv6_cidr_blocks": [],
    "dest_sgs": []
  },
  "awseb_e_t2wrbbxesn_stack_awsebloadbalancersecuritygroup_1sz1_0": {
    "sg": "awseb_e_t2wrbbxesn_stack_awsebloadbalancersecuritygroup_1sz1",
    "protocol": "tcp",
    "from_port": 80,
    "to_port": 80,
    "cidr_blocks": [
      "0.0.0.0/0"
    ],
    "ipv6_cidr_blocks": [],
    "dest_sgs": []
  }
}
}
